### ISSUE TITLE
wrong hash for files where size % 64 == 56

### ISSUE THREAD

**Issue by asarandi** [stephen-gardner/ssl_md5#2]
https://github.com/stephen-gardner/ssl_md5/blob/2959d7e069b547d0724f76e9c1fdf4fc8e0879ba/src/sha256.c#L146
please update to
`ctx->buff[bytes++] = 0x80;`

**Comment by stephen-gardner** [comment]
Resolved: https://github.com/stephen-gardner/ssl_md5/pull/4
